name: flutter_app
description: "This is my first Flutter mobile application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  intl: ^0.19.0
  path_provider: ^2.1.2
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  http: ^1.2.0
  animate_do: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/sounds/
    - assets/images/avatar.png

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf